import pandas as pd
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

DATA_DIR = BASE_DIR / "data"


OUTPUT_DIR = BASE_DIR / "output"
df_customers = pd.read_csv(DATA_DIR / "customers.csv")


# Load customers data
df_customers = pd.read_csv(DATA_DIR / "customers.csv")

# Load products data
df_products = pd.read_csv(DATA_DIR / "products.csv")

# # Load orders data
df_orders = pd.read_csv(DATA_DIR / "orders.csv")


# Display the data
print("Customers:")
print(df_customers)

print("\nProducts:")
print(df_products)

print("\nOrders:")
print(df_orders)


# Check number of rows and columns
print("Customers Shape:", df_customers.shape)
print("Products Shape:", df_products.shape)
print("Orders Shape:", df_orders.shape)

# Check column names
print("Customer Columns:", df_customers.columns)
print("Product Columns:", df_products.columns)
print("Order Columns:", df_orders.columns)


# Check data types and missing values
print(df_customers.info())
print(df_products.info())
print(df_orders.info())

print("Missing values in customers:")
print(df_customers.isnull().sum())

print("Missing values in products:")
print(df_products.isnull().sum())

print("Missing values in orders:")
print(df_orders.isnull().sum())


print("Duplicate customers:", df_customers.duplicated().sum())
print("Duplicate products:", df_products.duplicated().sum())
print("Duplicate orders:", df_orders.duplicated().sum())


#Date Transformation
df_orders["OrderDate"] = pd.to_datetime(df_orders["OrderDate"])
print(df_orders["OrderDate"])

#Merging 
df_merged = pd.merge(
    df_orders,
    df_customers,
    on="CustomerID",
    how="inner"
)

print(df_merged)

#Merged products
df_merged = pd.merge(
    df_merged,
    df_products,
    on="ProductID",
    how="inner"
)

print(df_merged)

#Create a new column: Revenue
df_merged["Revenue"] = (
    df_merged["Quantity"] * df_merged["Price"]
)

print(df_merged)

df_merged.to_csv(
     OUTPUT_DIR / "final_sales.csv",
     index=False
)

# ============================================================
# Find Customer with Highest Revenue
# ============================================================

# Group data by CustomerID and Customer Name
# Then calculate total revenue generated by each customer

customer_revenue = (
    df_merged
    .groupby(["CustomerID", "Name"])["Revenue"]
    .sum()
    .sort_values(ascending=False)
)

customer_revenue.to_csv(
    OUTPUT_DIR / "customer_revenue.csv",
    index=False
)

# Display revenue generated by each customer

print("Revenue by Customer:")
print(customer_revenue)


# Get the customer with the highest revenue

highest_revenue_customer = customer_revenue.head(1)

print("\nCustomer with Highest Revenue:")
print(highest_revenue_customer)


# ============================================================
# Find City with Highest Revenue
# ============================================================

# Calculate Revenue
# Revenue = Quantity * Price

df_merged["Revenue"] = df_merged["Quantity"] * df_merged["Price"]


# Group data by City
# Then calculate total revenue generated by each city

city_revenue = (
    df_merged
    .groupby("City")["Revenue"]
    .sum()
    .sort_values(ascending=False)
)

city_revenue.to_csv(
    OUTPUT_DIR / "city_revenue.csv",
    index=False
)

# Display revenue generated by each city

print("Revenue by City:")
print(city_revenue)


# Get the city with the highest revenue

highest_revenue_city = city_revenue.head(1)

print("\nCity with Highest Revenue:")
print(highest_revenue_city)


# ============================================================
# Find Category with Highest Revenue
# ============================================================

# Calculate Revenue
# Revenue = Quantity * Price

df_merged["Revenue"] = df_merged["Quantity"] * df_merged["Price"]


# Group data by Category
# Then calculate total revenue generated by each category

category_revenue = (
    df_merged
    .groupby("Category")["Revenue"]
    .sum()
    .sort_values(ascending=False)
)

category_revenue.to_csv(
    OUTPUT_DIR / "category_revenue.csv",
    index=False
)


# Display revenue generated by each category

print("Revenue by Category:")
print(category_revenue)


# Get the category with the highest revenue

highest_revenue_category = category_revenue.head(1)

print("\nCategory with Highest Revenue:")
print(highest_revenue_category)

# ============================================================
# Find Total Revenue
# ============================================================

# Calculate Revenue for each order
# Revenue = Quantity * Price

df_merged["Revenue"] = df_merged["Quantity"] * df_merged["Price"]


# Calculate total revenue from all orders

total_revenue = df_merged["Revenue"].sum()


# Display total revenue

print("Total Revenue:", total_revenue)

# ============================================================
# Find Average Order Value
# ============================================================

# Calculate Revenue for each order
# Revenue = Quantity * Price

df_merged["Revenue"] = df_merged["Quantity"] * df_merged["Price"]


# Calculate Average Order Value

average_order_value = df_merged["Revenue"].mean()


# Display Average Order Value

print("Average Order Value:", average_order_value)

# ============================================================
# Find Total Quantity Sold for Each Product
# ============================================================

# Group by ProductName
# Then calculate the total quantity sold

product_quantity = (
    df_merged
    .groupby("ProductName")["Quantity"]
    .sum()
    .sort_values(ascending=False)
)

product_quantity.to_csv(
    OUTPUT_DIR / "product_quantity.csv",
    index=False
)

# Display total quantity sold for each product

print("Total Quantity Sold by Product:")
print(product_quantity)

total_revenue = df_merged["Revenue"].sum()

average_order_value = df_merged["Revenue"].mean()


summary = pd.DataFrame({
    "Metric": [
        "Total Revenue",
        "Average Order Value"
    ],
    "Value": [
        total_revenue,
        average_order_value
    ]
})


summary.to_csv(
    OUTPUT_DIR / "summary.csv",
    index=False
)